
var Module = (() => {
  var _scriptName = typeof document != 'undefined' ? document.currentScript?.src : undefined;
  if (typeof __filename != 'undefined') _scriptName = _scriptName || __filename;
  return (
function(moduleArg = {}) {
  var moduleRtn;

var f=moduleArg,aa,ba,ca=new Promise((a,b)=>{aa=a;ba=b}),da="object"==typeof window,ea="undefined"!=typeof WorkerGlobalScope,fa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type;f.noInitialRun=!0;var ha=Object.assign({},f),ia=[],ja="./this.program",ka=(a,b)=>{throw b;},p="",la,ma;
if(fa){var fs=require("fs");require("path");p=__dirname+"/";ma=a=>{a=na(a)?new URL(a):a;return fs.readFileSync(a)};la=async a=>{a=na(a)?new URL(a):a;return fs.readFileSync(a,void 0)};!f.thisProgram&&1<process.argv.length&&(ja=process.argv[1].replace(/\\/g,"/"));ia=process.argv.slice(2);ka=(a,b)=>{process.exitCode=a;throw b;}}else if(da||ea)ea?p=self.location.href:"undefined"!=typeof document&&document.currentScript&&(p=document.currentScript.src),_scriptName&&(p=_scriptName),p.startsWith("blob:")?
p="":p=p.substr(0,p.replace(/[?#].*/,"").lastIndexOf("/")+1),ea&&(ma=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),la=async a=>{if(na(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();
throw Error(b.status+" : "+b.url);};var oa=console.log.bind(console),r=console.error.bind(console);Object.assign(f,ha);ha=null;var pa,qa=!1,ra,u,w,sa,x,y,z;function ta(){var a=pa.buffer;f.HEAP8=u=new Int8Array(a);f.HEAP16=sa=new Int16Array(a);f.HEAPU8=w=new Uint8Array(a);f.HEAPU16=new Uint16Array(a);f.HEAP32=x=new Int32Array(a);f.HEAPU32=y=new Uint32Array(a);f.HEAPF32=new Float32Array(a);f.HEAPF64=new Float64Array(a);f.HEAP64=z=new BigInt64Array(a);f.HEAPU64=new BigUint64Array(a)}
var ua=[],va=[],wa=[],xa=[],ya=0,za=null;function Aa(){ya--;if(0==ya&&za){var a=za;za=null;a()}}function A(a){a="Aborted("+a+")";r(a);qa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var Ba=a=>a.startsWith("data:application/octet-stream;base64,"),na=a=>a.startsWith("file://"),Ca;async function Da(a){try{var b=await la(a);return new Uint8Array(b)}catch{}if(ma)a=ma(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Ea(a,b){try{var c=await Da(a);return await WebAssembly.instantiate(c,b)}catch(d){r(`failed to asynchronously prepare wasm: ${d}`),A(d)}}async function Fa(a){var b=Ca;if(!("function"!=typeof WebAssembly.instantiateStreaming||Ba(b)||na(b)||fa)&&"function"==typeof fetch)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){r(`wasm streaming compile failed: ${d}`),r("falling back to ArrayBuffer instantiation")}return Ea(b,a)}
class Ga{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Ha=a=>{for(;0<a.length;)a.shift()(f)},Ia="undefined"!=typeof TextDecoder?new TextDecoder:void 0,B=(a,b=0)=>{for(var c=b+NaN,d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Ia)return Ia.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=
String.fromCharCode(e)}return c},Ja=[],Ka=0,D=0;class La{constructor(a){this.nb=a;this.wa=a-24}Pa(a,b){y[this.wa+16>>2]=0;y[this.wa+4>>2]=a;y[this.wa+8>>2]=b}}
var Oa=a=>{var b=D;if(!b)return Ma(0),0;var c=new La(b);y[c.wa+16>>2]=b;var d=y[c.wa+4>>2];if(!d)return Ma(0),b;for(var e of a){if(0===e||e===d)break;if(Na(e,d,c.wa+16))return Ma(e),b}Ma(d);return b},E=()=>{var a=x[+Pa>>2];Pa+=4;return a},Qa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},F=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Qa(a.split("/").filter(d=>!!d),!b).join("/"))||
b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ra=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},Sa=a=>{if("/"===a)return"/";a=F(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Ua=(...a)=>F(a.join("/")),Va=(a,b)=>F(a+"/"+b),Wa=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(fa)try{var a=
require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}A("initRandomDevice")},Xa=a=>(Xa=Wa())(a),Ya=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:G.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Qa(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Za=(a,b)=>{function c(h){for(var k=0;k<h.length&&
""===h[k];k++);for(var m=h.length-1;0<=m&&""===h[m];m--);return k>m?[]:h.slice(k,m-k+1)}a=Ya(a).substr(1);b=Ya(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,g=0;g<d;g++)if(a[g]!==b[g]){e=g;break}d=[];for(g=e;g<a.length;g++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},$a=[],ab=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},bb=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;
d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var k=a.charCodeAt(++g);h=65536+((h&1023)<<10)|k&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e};function cb(a){var b=Array(ab(a)+1);a=bb(a,b,0,b.length);b.length=a;return b}var db=[];
function eb(a,b){db[a]={input:[],output:[],Ea:b};fb(a,gb)}
var gb={open(a){var b=db[a.node.rdev];if(!b)throw new G.oa(43);a.tty=b;a.seekable=!1},close(a){a.tty.Ea.fsync(a.tty)},fsync(a){a.tty.Ea.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Ea.pb)throw new G.oa(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.Ea.pb(a.tty)}catch(k){throw new G.oa(29);}if(void 0===h&&0===e)throw new G.oa(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Ea.eb)throw new G.oa(60);try{for(var e=0;e<d;e++)a.tty.Ea.eb(a.tty,
b[c+e])}catch(g){throw new G.oa(29);}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},hb={pb(){a:{if(!$a.length){var a=null;if(fa){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}$a=cb(a)}a=$a.shift()}return a},eb(a,b){null===b||10===
b?(oa(B(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(oa(B(a.output)),a.output=[])},Lb(){return{Yb:25856,$b:5,Xb:191,Zb:35387,Wb:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Mb(){return 0},Nb(){return[24,80]}},ib={eb(a,b){null===b||10===b?(r(B(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(r(B(a.output)),a.output=[])}};
function jb(a,b){var c=a.ra?a.ra.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.ra,a.ra=new Uint8Array(b),0<a.ta&&a.ra.set(c.subarray(0,a.ta),0))}
var H={Da:null,sa(){return H.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||G.isFIFO(c))throw new G.oa(63);H.Da||(H.Da={dir:{node:{ya:H.pa.ya,ua:H.pa.ua,lookup:H.pa.lookup,Aa:H.pa.Aa,rename:H.pa.rename,unlink:H.pa.unlink,rmdir:H.pa.rmdir,readdir:H.pa.readdir,symlink:H.pa.symlink},stream:{va:H.qa.va}},file:{node:{ya:H.pa.ya,ua:H.pa.ua},stream:{va:H.qa.va,read:H.qa.read,write:H.qa.write,Oa:H.qa.Oa,Ia:H.qa.Ia,La:H.qa.La}},link:{node:{ya:H.pa.ya,ua:H.pa.ua,readlink:H.pa.readlink},
stream:{}},jb:{node:{ya:H.pa.ya,ua:H.pa.ua},stream:G.Db}});c=G.createNode(a,b,c,d);J(c.mode)?(c.pa=H.Da.dir.node,c.qa=H.Da.dir.stream,c.ra={}):G.isFile(c.mode)?(c.pa=H.Da.file.node,c.qa=H.Da.file.stream,c.ta=0,c.ra=null):40960===(c.mode&61440)?(c.pa=H.Da.link.node,c.qa=H.Da.link.stream):8192===(c.mode&61440)&&(c.pa=H.Da.jb.node,c.qa=H.Da.jb.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.ra[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},hc(a){return a.ra?a.ra.subarray?a.ra.subarray(0,a.ta):new Uint8Array(a.ra):
new Uint8Array(0)},pa:{ya(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;J(a.mode)?b.size=4096:G.isFile(a.mode)?b.size=a.ta:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.Fa=4096;b.blocks=Math.ceil(b.size/b.Fa);return b},ua(a,b){for(var c of["mode","atime","mtime","ctime"])b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.ta!=b&&(0==b?(a.ra=null,a.ta=
0):(c=a.ra,a.ra=new Uint8Array(b),c&&a.ra.set(c.subarray(0,Math.min(b,a.ta))),a.ta=b)))},lookup(){throw H.mb;},Aa(a,b,c,d){return H.createNode(a,b,c,d)},rename(a,b,c){try{var d=M(b,c)}catch(g){}if(d){if(J(a.mode))for(var e in d.ra)throw new G.oa(55);kb(d)}delete a.parent.ra[a.name];b.ra[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.ra[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=M(a,b),d;for(d in c.ra)throw new G.oa(55);delete a.ra[b];a.ctime=a.mtime=
Date.now()},readdir(a){return[".","..",...Object.keys(a.ra)]},symlink(a,b,c){a=H.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new G.oa(28);return a.link}},qa:{read(a,b,c,d,e){var g=a.node.ra;if(e>=a.node.ta)return 0;a=Math.min(a.node.ta-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write(a,b,c,d,e,g){b.buffer===u.buffer&&(g=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.ra||a.ra.subarray)){if(g)return a.ra=
b.subarray(c,c+d),a.ta=d;if(0===a.ta&&0===e)return a.ra=b.slice(c,c+d),a.ta=d;if(e+d<=a.ta)return a.ra.set(b.subarray(c,c+d),e),d}jb(a,e+d);if(a.ra.subarray&&b.subarray)a.ra.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.ra[e+g]=b[c+g];a.ta=Math.max(a.ta,e+d);return d},va(a,b,c){1===c?b+=a.position:2===c&&G.isFile(a.node.mode)&&(b+=a.node.ta);if(0>b)throw new G.oa(28);return b},Oa(a,b,c){jb(a.node,b+c);a.node.ta=Math.max(a.node.ta,b+c)},Ia(a,b,c,d,e){if(!G.isFile(a.node.mode))throw new G.oa(43);
a=a.node.ra;if(e&2||!a||a.buffer!==u.buffer){d=!0;A();e=void 0;if(!e)throw new G.oa(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);u.set(a,e)}}else d=!1,e=a.byteOffset;return{wa:e,Ab:d}},La(a,b,c,d){H.qa.write(a,b,0,d,c,!1);return 0}}},lb=async a=>{a=await la(a);return new Uint8Array(a)},mb=[],nb=(a,b,c,d)=>{"undefined"!=typeof Browser&&Browser.Pa();var e=!1;mb.forEach(g=>{!e&&g.canHandle(b)&&(g.handle(a,b,c,d),e=!0)});return e},ob=(a,b)=>{var c=
0;a&&(c|=365);b&&(c|=146);return c},pb={EPERM:63,ENOENT:44,ESRCH:71,EINTR:27,EIO:29,ENXIO:60,E2BIG:1,ENOEXEC:45,EBADF:8,ECHILD:12,EAGAIN:6,EWOULDBLOCK:6,ENOMEM:48,EACCES:2,EFAULT:21,ENOTBLK:105,EBUSY:10,EEXIST:20,EXDEV:75,ENODEV:43,ENOTDIR:54,EISDIR:31,EINVAL:28,ENFILE:41,EMFILE:33,ENOTTY:59,ETXTBSY:74,EFBIG:22,ENOSPC:51,ESPIPE:70,EROFS:69,EMLINK:34,EPIPE:64,EDOM:18,ERANGE:68,ENOMSG:49,EIDRM:24,ECHRNG:106,EL2NSYNC:156,EL3HLT:107,EL3RST:108,ELNRNG:109,EUNATCH:110,ENOCSI:111,EL2HLT:112,EDEADLK:16,ENOLCK:46,
EBADE:113,EBADR:114,EXFULL:115,ENOANO:104,EBADRQC:103,EBADSLT:102,EDEADLOCK:16,EBFONT:101,ENOSTR:100,ENODATA:116,ETIME:117,ENOSR:118,ENONET:119,ENOPKG:120,EREMOTE:121,ENOLINK:47,EADV:122,ESRMNT:123,ECOMM:124,EPROTO:65,EMULTIHOP:36,EDOTDOT:125,EBADMSG:9,ENOTUNIQ:126,EBADFD:127,EREMCHG:128,ELIBACC:129,ELIBBAD:130,ELIBSCN:131,ELIBMAX:132,ELIBEXEC:133,ENOSYS:52,ENOTEMPTY:55,ENAMETOOLONG:37,ELOOP:32,EOPNOTSUPP:138,EPFNOSUPPORT:139,ECONNRESET:15,ENOBUFS:42,EAFNOSUPPORT:5,EPROTOTYPE:67,ENOTSOCK:57,ENOPROTOOPT:50,
ESHUTDOWN:140,ECONNREFUSED:14,EADDRINUSE:3,ECONNABORTED:13,ENETUNREACH:40,ENETDOWN:38,ETIMEDOUT:73,EHOSTDOWN:142,EHOSTUNREACH:23,EINPROGRESS:26,EALREADY:7,EDESTADDRREQ:17,EMSGSIZE:35,EPROTONOSUPPORT:66,ESOCKTNOSUPPORT:137,EADDRNOTAVAIL:4,ENETRESET:39,EISCONN:30,ENOTCONN:53,ETOOMANYREFS:141,EUSERS:136,EDQUOT:19,ESTALE:72,ENOTSUP:138,ENOMEDIUM:148,EILSEQ:25,EOVERFLOW:61,ECANCELED:11,ENOTRECOVERABLE:56,EOWNERDEAD:62,ESTRPIPE:135};
function N(a){try{return a()}catch(b){if(!b.code)throw b;if("UNKNOWN"===b.code)throw new G.oa(28);throw new G.oa(pb[b.code]);}}function qb(a){return N(()=>{var b=fs.lstatSync(a).mode;P.Ta&&(b|=(b&292)>>2);return b})}function Q(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.sa.Ma.root);b.reverse();return Ua(...b)}
var P={Ta:!1,ib(){P.Ta=!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);P.ob={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,256:a.O_NOCTTY,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY,131072:a.O_NOFOLLOW}},sa(a){return P.createNode(null,"/",qb(a.Ma.root),0)},createNode(a,b,c){if(!J(c)&&!G.isFile(c)&&40960!==(c&61440))throw new G.oa(28);a=G.createNode(a,b,c);a.pa=P.pa;a.qa=P.qa;return a},pa:{ya(a){var b=Q(a),c;N(()=>c=fs.lstatSync(b));P.Ta&&(c.Fa||
(c.Fa=4096),c.blocks||(c.blocks=(c.size+c.Fa-1)/c.Fa|0),c.mode|=(c.mode&292)>>2);return{dev:c.dev,ino:c.ino,mode:c.mode,nlink:c.nlink,uid:c.uid,gid:c.gid,rdev:c.rdev,size:c.size,atime:c.atime,mtime:c.mtime,ctime:c.ctime,Fa:c.Fa,blocks:c.blocks}},ua(a,b){var c=Q(a);N(()=>{if(void 0!==b.mode){var d=b.mode;P.Ta&&(d&=384);fs.chmodSync(c,d);a.mode=b.mode}void 0!==b.size&&fs.truncateSync(c,b.size)})},lookup(a,b){var c=Q(a);c=F(c+"/"+b);c=qb(c);return P.createNode(a,b,c)},Aa(a,b,c,d){var e=P.createNode(a,
b,c,d),g=Q(e);N(()=>{J(e.mode)?fs.mkdirSync(g,e.mode):fs.writeFileSync(g,"",{mode:e.mode})});return e},rename(a,b,c){var d=Q(a),e=Va(Q(b),c);try{G.unlink(e)}catch(g){}N(()=>fs.renameSync(d,e));a.name=c},unlink(a,b){var c=Va(Q(a),b);N(()=>fs.unlinkSync(c))},rmdir(a,b){var c=Va(Q(a),b);N(()=>fs.rmdirSync(c))},readdir(a){var b=Q(a);return N(()=>fs.readdirSync(b))},symlink(a,b,c){var d=Va(Q(a),b);N(()=>fs.symlinkSync(c,d))},readlink(a){var b=Q(a);return N(()=>fs.readlinkSync(b))},hb(a){var b=N(()=>fs.mc(a));
b.Ib=b.Bb;return b}},qa:{open(a){var b=Q(a.node);N(()=>{if(G.isFile(a.node.mode)){a.Ka.tb=1;var c=fs,d=c.openSync,e=a.flags;e&=-2721793;var g=0,h;for(h in P.ob)e&h&&(g|=P.ob[h],e^=h);if(e)throw new G.oa(28);a.Ra=d.call(c,b,g)}})},close(a){N(()=>{G.isFile(a.node.mode)&&a.Ra&&0===--a.Ka.tb&&fs.closeSync(a.Ra)})},Fb(a){a.Ka.tb++},read(a,b,c,d,e){return 0===d?0:N(()=>fs.readSync(a.Ra,new Int8Array(b.buffer,c,d),0,d,e))},write(a,b,c,d,e){return N(()=>fs.writeSync(a.Ra,new Int8Array(b.buffer,c,d),0,d,e))},
va(a,b,c){var d=b;1===c?d+=a.position:2===c&&G.isFile(a.node.mode)&&N(()=>{d+=fs.fstatSync(a.Ra).size});if(0>d)throw new G.oa(28);return d},Ia(a,b,c){if(!G.isFile(a.node.mode))throw new G.oa(43);A();P.qa.read(a,u,void 0,b,c);return{wa:void 0,Ab:!0}},La(a,b,c,d){P.qa.write(a,b,0,d,c,!1);return 0}}},R={Wa:16895,Na:33279,gb:null,sa(a){function b(g){g=g.split("/");for(var h=d,k=0;k<g.length-1;k++){var m=g.slice(0,k+1).join("/");let n,l;(n=e)[l=m]||(n[l]=R.createNode(h,g[k],R.Wa,0));h=e[m]}return h}function c(g){g=
g.split("/");return g[g.length-1]}ea||A();R.gb??(R.gb=new FileReaderSync);var d=R.createNode(null,"/",R.Wa,0),e={};Array.prototype.forEach.call(a.Ma.files||[],function(g){R.createNode(b(g.name),c(g.name),R.Na,0,g,g.lastModifiedDate)});(a.Ma.blobs||[]).forEach(g=>{R.createNode(b(g.name),c(g.name),R.Na,0,g.data)});(a.Ma.packages||[]).forEach(g=>{g.metadata.files.forEach(h=>{var k=h.filename.substr(1);R.createNode(b(k),c(k),R.Na,0,g.blob.slice(h.start,h.end))})});return d},createNode(a,b,c,d,e,g){d=
G.createNode(a,b,c);d.mode=c;d.pa=R.pa;d.qa=R.qa;d.atime=d.mtime=d.ctime=(g||new Date).getTime();R.Na!==R.Wa||A();c===R.Na?(d.size=e.size,d.ra=e):(d.size=4096,d.ra={});a&&(a.ra[b]=d);return d},pa:{ya(a){return{dev:1,ino:a.id,mode:a.mode,nlink:1,uid:0,gid:0,rdev:0,size:a.size,atime:new Date(a.atime),mtime:new Date(a.mtime),ctime:new Date(a.ctime),Fa:4096,blocks:Math.ceil(a.size/4096)}},ua(a,b){for(const c of["mode","atime","mtime","ctime"])b[c]&&(a[c]=b[c])},lookup(){throw new G.oa(44);},Aa(){throw new G.oa(63);
},rename(){throw new G.oa(63);},unlink(){throw new G.oa(63);},rmdir(){throw new G.oa(63);},readdir(a){var b=[".",".."],c;for(c of Object.keys(a.ra))b.push(c);return b},symlink(){throw new G.oa(63);}},qa:{read(a,b,c,d,e){if(e>=a.node.size)return 0;a=a.node.ra.slice(e,e+d);d=R.gb.readAsArrayBuffer(a);b.set(new Uint8Array(d),c);return a.size},write(){throw new G.oa(29);},va(a,b,c){1===c?b+=a.position:2===c&&G.isFile(a.node.mode)&&(b+=a.node.size);if(0>b)throw new G.oa(28);return b}}};
function fb(a,b){G.lb[a]={qa:b}}function J(a){return 16384===(a&61440)}function M(a,b){var c=J(a.mode)?(c=rb(a,"x"))?c:a.pa.lookup?0:2:54;if(c)throw new G.oa(c);for(c=G.Ca[sb(a.id,b)];c;c=c.Ja){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return G.lookup(a,b)}function kb(a){var b=sb(a.parent.id,a.name);if(G.Ca[b]===a)G.Ca[b]=a.Ja;else for(b=G.Ca[b];b;){if(b.Ja===a){b.Ja=a.Ja;break}b=b.Ja}}
function S(a,b={}){if(!a)return{path:"",node:null};b.Sa??(b.Sa=!0);"/"===a.charAt(0)||(a=G.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(k=>!!k&&"."!==k);for(var d=G.root,e="/",g=0;g<a.length;g++){var h=g===a.length-1;if(h&&b.parent)break;if(".."===a[g])e=Ra(e),d=d.parent;else{e=F(e+"/"+a[g]);try{d=M(d,a[g])}catch(k){if(44===k?.xa&&h&&b.Qb)return{path:e};throw k;}!d.Ba||h&&!b.Sa||(d=d.Ba.root);if(40960===(d.mode&61440)&&(!h||b.za)){if(!d.pa.readlink)throw new G.oa(52);d=d.pa.readlink(d);
"/"===d.charAt(0)||(d=Ra(e)+"/"+d);a=d+"/"+a.slice(g+1).join("/");continue a}}}return{path:e,node:d}}throw new G.oa(32);}function tb(a){for(var b;;){if(G.qb(a))return a=a.sa.rb,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function sb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%G.Ca.length}function ub(a){var b=sb(a.parent.id,a.name);a.Ja=G.Ca[b];G.Ca[b]=a}function vb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function rb(a,b){if(G.Ya)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function wb(a,b){if(!J(a.mode))return 54;try{return M(a,b),20}catch(c){}return rb(a,"wx")}function xb(a,b,c){try{var d=M(a,b)}catch(e){return e.xa}if(a=rb(a,"wx"))return a;if(c){if(!J(d.mode))return 54;if(G.qb(d)||tb(d)===G.cwd())return 10}else if(J(d.mode))return 31;return 0}function U(a){a=G.Kb(a);if(!a)throw new G.oa(8);return a}
function yb(a,b=-1){a=Object.assign(new G.yb,a);if(-1==b)a:{for(b=0;b<=G.zb;b++)if(!G.streams[b])break a;throw new G.oa(33);}a.fd=b;return G.streams[b]=a}function zb(a,b=-1){a=yb(a,b);a.qa?.Fb?.(a);return a}function Ab(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.Qa)}return b}function Bb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return G.Aa(a,b|8192,c)}
function Cb(){G.mkdir("/dev");fb(G.Ha(1,3),{read:()=>0,write:(d,e,g,h)=>h,va:()=>0});Bb("/dev/null",G.Ha(1,3));eb(G.Ha(5,0),hb);eb(G.Ha(6,0),ib);Bb("/dev/tty",G.Ha(5,0));Bb("/dev/tty1",G.Ha(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Xa(a).byteLength)